name: talekeepers-tome
author: alyphen
version: ${version}
main: net.arvandor.talekeeper.TalekeepersTome
api-version: 1.19
depend:
  - rpk-core-bukkit
  - rpk-player-lib-bukkit
  - rpk-character-lib-bukkit
  - rpk-notification-lib-bukkit
  - rpk-stat-lib-bukkit
  - rpk-language-lib-bukkit
  - numinous-treasury
commands:
  character:
    description: |
      Character management command
      /character context - Views the character you are currently creating
      /character context name set - Sets the name in the character creation context
      /character context name hide - Hides the name in the character creation context
      /character context name unhide - Shows the name in the character creation context
      /character context profile hide - Hides the profile in the character creation context
      /character context profile unhide - Shows the profile in the character creation context
      /character context pronouns add - Adds a pronoun set to the character creation context
      /character context pronouns remove - Removes a pronoun set from the character creation context
      /character context pronouns setchance - Sets the chance of a pronoun set being used in the character creation context
      /character context ancestry set - Sets the ancestry in the character creation context
      /character context ancestry hide - Hides the ancestry in the character creation context
      /character context ancestry unhide - Shows the ancestry in the character creation context
      /character context subancestry set - Sets the subancestry in the character creation context
      /character context class set - Sets the class in the character creation context
      /character context background set - Sets the background in the character creation context
      /character context alignment set - Sets the alignment in the character creation context
      /character context abilities set - Sets the abilities in the character creation context
      /character context description set - Sets the description in the character creation context
      /character context description extend - Extends the description in the character creation context
      /character context description hide - Hides the description in the character creation context
      /character context description unhide - Shows the description in the character creation context
      /character context height set - Sets the height in the character creation context
      /character context height hide - Hides the height in the character creation context
      /character context height unhide - Shows the height in the character creation context
      /character context weight set - Sets the weight in the character creation context
      /character context weight hide - Hides the weight in the character creation context
      /character context weight unhide - Shows the weight in the character creation context
      /character card (player) - Views your character card, or the character card of another player
      /character name set - Sets your character's name
      /character name hide - Hides your character's name
      /character name unhide - Shows your character's name
      /character profile hide - Hides your character's profile
      /character profile unhide - Shows your character's profile
      /character pronouns add - Adds a pronoun set to your character
      /character pronouns remove - Removes a pronoun set from your character
      /character pronouns setchance - Sets the chance of a pronoun set being used by your character
      /character ancestry hide - Hides your character's ancestry
      /character ancestry unhide - Shows your character's ancestry
      /character alignment set - Sets your character's alignment
      /character description set - Sets your character's description
      /character description extend - Extends your character's description
      /character description hide - Hides your character's description
      /character description unhide - Shows your character's description
      /character height set - Sets your character's height
      /character height hide - Hides your character's height
      /character height unhide - Shows your character's height
      /character weight set - Sets your character's weight
      /character weight hide - Hides your character's weight
      /character weight unhide - Shows your character's weight
      /character requests - Views new character creation requests
      /character requests accept - Accepts a new character creation request
      /character requests decline - Declines a new character creation request
    usage: /<command> [context]
    aliases: [char, c]
  ancestry:
    description: |
      Ancestry management command
      /ancestry traits [ancestry] (page) - Lists the traits of an ancestry
    usage: /<command> [traits]
    aliases: [race, species]
  background:
    description: |
      Background management command
      /background view [background] - Views the details of a background
    usage: /<command> [view]
    aliases: [bg]
  choice:
    description: |
      Choice management command
      /choice list - Lists pending choices
      /choice view [choice id] - Views a choice
      /choice select [choice id] [option id] - Selects an option for a choice
  hp:
    description: |
      Hit Points command
      /hp - View your HP
      /hp decrease - Decrease your HP
      /hp increase - Increase your HP
      /hp share - Display your HP to nearby players
      /hp [player] - View another player's HP
      /hp decrease [player] - Decrease another player's HP
      /hp increase [player] - Increase another player's HP
permissions:
  talekeeper.commands.character.requests:
    description: Allows viewing and accepting or declining new character requests
    default: op
  talekeeper.commands.hp.view.other:
    description: Allows viewing other players' HP
    default: op
  talekeeper.commands.hp.set.other:
    description: Allows setting other players' HP
    default: op